package com.mvp.myapplication.utils

import com.mvp.myapplication.data.models.api.ModelAttr

class AttrList() {

    val attrList = ArrayList<ModelAttr>()

    init {
        attrList.add(ModelAttr("a-line", "линии"))
        attrList.add(ModelAttr("abstract", "абстрактный"))
        attrList.add(ModelAttr("abstractchevron", "абстрактные аппликации"))
        attrList.add(ModelAttr("abstractchevronprint", "абстрактные аппликации"))
        attrList.add(ModelAttr("abstractdiamond", "абстрактный со стразами"))
        attrList.add(ModelAttr("abstractfloral", "абстрактный цветочный принт"))
        attrList.add(ModelAttr("abstractfloralprint", "абстрактный цветочный принт"))
        attrList.add(ModelAttr("abstractgeo", "аннотация гео"))
        attrList.add(ModelAttr("abstractgeoprint", "абстрактный гео печати"))
        attrList.add(ModelAttr("abstractpaisley", "абстрактный Пейсли"))
        attrList.add(ModelAttr("abstractpattern", "абстрактный принт"))
        attrList.add(ModelAttr("abstractprint", "абстрактный принт"))
        attrList.add(ModelAttr("abstractprinted", "абстрактный принт"))
        attrList.add(ModelAttr("abstractstripe", "абстрактная полоса"))
        attrList.add(ModelAttr("acid", "кислотный"))
        attrList.add(ModelAttr("acidwash", "кислотный  размытый"))
        attrList.add(ModelAttr("americana", "Американский"))
        attrList.add(ModelAttr("angeles", "Анджелес"))
        attrList.add(ModelAttr("animal", "животный принт"))
        attrList.add(ModelAttr("animalprint", "животный принт"))
        attrList.add(ModelAttr("ankle", "лодыжка"))
        attrList.add(ModelAttr("applique", "аппликация"))
        attrList.add(ModelAttr("arrowcollar", "трехцветный"))
        attrList.add(ModelAttr("art", "искусство"))
        attrList.add(ModelAttr("asymmetric", "асимметричный"))
        attrList.add(ModelAttr("asymmetrical", "асимметричный"))
        attrList.add(ModelAttr("asymmetricalhem", "асимметричный"))
        attrList.add(ModelAttr("athletic", "спортивный"))
        attrList.add(ModelAttr("audrey", "Одри"))
        attrList.add(ModelAttr("babe", "детский"))
        attrList.add(ModelAttr("babydoll", "кукла"))
        attrList.add(ModelAttr("backbow", "готовый образ"))
        attrList.add(ModelAttr("backcutout", "вырез на спине"))
        attrList.add(ModelAttr("backknit", "с подсветкой"))
        attrList.add(ModelAttr("backlace", "кружева на спине"))
        attrList.add(ModelAttr("backstriped", "вернуться в полоску"))
        attrList.add(ModelAttr("backless", "сзади короткий"))
        attrList.add(ModelAttr("baja", "абстрактный"))
        attrList.add(ModelAttr("bandage", "повязка"))
        attrList.add(ModelAttr("bandana", "бандана"))
        attrList.add(ModelAttr("bandanaprint", "спец. одежда"))
        attrList.add(ModelAttr("barbie", "Барби"))
        attrList.add(ModelAttr("baroque", "принт"))
        attrList.add(ModelAttr("baroqueprint", "принт"))
        attrList.add(ModelAttr("baseball", "бейсбол"))
        attrList.add(ModelAttr("basic", "Базовый"))
        attrList.add(ModelAttr("basquiat", "Баския"))
        attrList.add(ModelAttr("batwing", "летучая мышь"))
        attrList.add(ModelAttr("beach", "пляжная"))
        attrList.add(ModelAttr("bead", "расшитый бисером"))
        attrList.add(ModelAttr("beaded", "взвинченный"))
        attrList.add(ModelAttr("beadedchiffon", "расшитый бисером шифоновое"))
        attrList.add(ModelAttr("beadedcollar", "воротник из бисера"))
        attrList.add(ModelAttr("beadedsheer", "бисер"))
        attrList.add(ModelAttr("beadedshift", "бисер"))
        attrList.add(ModelAttr("beatles", "Битлз"))
        attrList.add(ModelAttr("bed", "кровать"))
        attrList.add(ModelAttr("bejeweled", "украшен драгоценными камнями"))
        attrList.add(ModelAttr("bell", "колокол"))
        attrList.add(ModelAttr("bell-sleeve", "колокол рукав"))
        attrList.add(ModelAttr("bella", "Белла"))
        attrList.add(ModelAttr("belted", "с поясом"))
        attrList.add(ModelAttr("beltedchiffon", "с поясом из шифона"))
        attrList.add(ModelAttr("beltedfloral", "с поясом цветочный принт"))
        attrList.add(ModelAttr("beltedfloralprint", "с поясом цветочный принт"))
        attrList.add(ModelAttr("beltedlace", "пояс из кружев"))
        attrList.add(ModelAttr("beltedmaxi", "с поясом макси"))
        attrList.add(ModelAttr("beltedplaid", "плед"))
        attrList.add(ModelAttr("bermuda", "Бермуды"))
        attrList.add(ModelAttr("bib", "доспехи"))
        attrList.add(ModelAttr("big", "большой"))
        attrList.add(ModelAttr("bike", "велосипед"))
        attrList.add(ModelAttr("biker", "мотоциклист"))
        attrList.add(ModelAttr("bird", "птица"))
        attrList.add(ModelAttr("birdprint", "птица"))
        attrList.add(ModelAttr("blah", "без смысла"))
        attrList.add(ModelAttr("bleach", "белый"))
        attrList.add(ModelAttr("bleached", "белый"))
        attrList.add(ModelAttr("bleacheddenim", "выбеленный деним"))
        attrList.add(ModelAttr("blurred", "размытый принт"))
        attrList.add(ModelAttr("boatneck", "декольте"))
        attrList.add(ModelAttr("bodycon", "офисный"))
        attrList.add(ModelAttr("bodyconmidi", "базовый"))
        attrList.add(ModelAttr("boho", "бохо"))
        attrList.add(ModelAttr("bold", "большой размер"))
        attrList.add(ModelAttr("botanical", "цветочный"))
        attrList.add(ModelAttr("botanicalprint", "цветочный принт"))
        attrList.add(ModelAttr("bow", "образ"))
        attrList.add(ModelAttr("bow-back", "образ"))
        attrList.add(ModelAttr("bow-front", "образ"))
        attrList.add(ModelAttr("box", "коробка"))
        attrList.add(ModelAttr("boxpleat", "складная коробка"))
        attrList.add(ModelAttr("box-pleated", "плиссе"))
        attrList.add(ModelAttr("boxy", "площадь"))
        attrList.add(ModelAttr("boxycrop", "объемный"))
        attrList.add(ModelAttr("boxyknit", "короткий джемпер"))
        attrList.add(ModelAttr("boxylace", "объемные кружева"))
        attrList.add(ModelAttr("boxypocket", "объемный карман"))
        attrList.add(ModelAttr("boxystriped", "свободный полосатый"))
        attrList.add(ModelAttr("boyfriend", "бойфренд"))
        attrList.add(ModelAttr("braided", "плетеный"))
        attrList.add(ModelAttr("breton", "Бретонская полоса"))
        attrList.add(ModelAttr("bretonstripe", "Бретонская полоса"))
        attrList.add(ModelAttr("brocade", "парча"))
        attrList.add(ModelAttr("brooklyn", "Бруклин"))
        attrList.add(ModelAttr("brooklynnets", "Бруклин"))
        attrList.add(ModelAttr("brushstroke", "искусственная грязь"))
        attrList.add(ModelAttr("brushstrokeprint", "абстрактный принт"))
        attrList.add(ModelAttr("burnout", "потёртости"))
        attrList.add(ModelAttr("bustier", "бюстье"))
        attrList.add(ModelAttr("butterfly", "бабочка"))
        attrList.add(ModelAttr("butterflyprint", "бабочка"))
        attrList.add(ModelAttr("button", "кнопка"))
        attrList.add(ModelAttr("button-front", "кнопки сзади"))
        attrList.add(ModelAttr("buttoned", "закрепленный"))
        attrList.add(ModelAttr("cable", "кабель"))
        attrList.add(ModelAttr("cableknit", "кабель"))
        attrList.add(ModelAttr("cable-knit", "кабель"))
        attrList.add(ModelAttr("caged", "в клетку"))
        attrList.add(ModelAttr("california", "без смысла"))
        attrList.add(ModelAttr("camera", "камера"))
        attrList.add(ModelAttr("cami", "космический"))
        attrList.add(ModelAttr("camicrop", "без смысла"))
        attrList.add(ModelAttr("camimaxi", "кульминация"))
        attrList.add(ModelAttr("camo", "камуфляжный"))
        attrList.add(ModelAttr("camouflage", "камуфляжный"))
        attrList.add(ModelAttr("candy", "конфета"))
        attrList.add(ModelAttr("canvas", "холст"))
        attrList.add(ModelAttr("cap-sleeve", "колпачок-втулка"))
        attrList.add(ModelAttr("capri", "Капри"))
        attrList.add(ModelAttr("cardio", "спортивный"))
        attrList.add(ModelAttr("cargo", "груз"))
        attrList.add(ModelAttr("cat", "кошка"))
        attrList.add(ModelAttr("chambray", "Шамбре"))
        attrList.add(ModelAttr("chambraydrawstring", "шамбре шнурок"))
        attrList.add(ModelAttr("checked", "доказанный"))
        attrList.add(ModelAttr("checkered", "проверять"))
        attrList.add(ModelAttr("cheetah", "гепард"))
        attrList.add(ModelAttr("chenille", "синель"))
        attrList.add(ModelAttr("chevron", "аппликация"))
        attrList.add(ModelAttr("chevronprint", "аппликация"))
        attrList.add(ModelAttr("chic", "шикарный"))
        attrList.add(ModelAttr("chiffon", "шифон"))
        attrList.add(ModelAttr("chiffonfloral", "шифон цветочный принт"))
        attrList.add(ModelAttr("chiffonlace", "шифон кружева"))
        attrList.add(ModelAttr("chiffonlayered", "шифон слоис"))
        attrList.add(ModelAttr("chiffonmaxi", "шифон"))
        attrList.add(ModelAttr("chiffonpaneled", "шифоновое со вставками"))
        attrList.add(ModelAttr("chiffonpleated", "шифон плиссированные"))
        attrList.add(ModelAttr("chiffonshift", "шифон"))
        attrList.add(ModelAttr("chiffonshirt", "шифон"))
        attrList.add(ModelAttr("chiffonsurplice", "шифон"))
        attrList.add(ModelAttr("chiffon-paneled", "шифон"))
        attrList.add(ModelAttr("chino", "чай"))
        attrList.add(ModelAttr("chunky", "плотный"))
        attrList.add(ModelAttr("chunkyknit", "плотная вязка"))
        attrList.add(ModelAttr("cinched", "предоставлена"))
        attrList.add(ModelAttr("circle", "круг"))
        attrList.add(ModelAttr("cities", "город"))
        attrList.add(ModelAttr("city", "город"))
        attrList.add(ModelAttr("civil", "кэжуал"))
        attrList.add(ModelAttr("clashist", "клаш"))
        attrList.add(ModelAttr("classic", "классический"))
        attrList.add(ModelAttr("classiccotton", "классический хлопок"))
        attrList.add(ModelAttr("classiccrew", "классический"))
        attrList.add(ModelAttr("classiccrewneck", "классический круглый вырез"))
        attrList.add(ModelAttr("classicdenim", "классический"))
        attrList.add(ModelAttr("classicfit", "классический крой"))
        attrList.add(ModelAttr("classicknit", "классический трикотаж"))
        attrList.add(ModelAttr("classicpocket", "классические карманы"))
        attrList.add(ModelAttr("classicskinny", "классический"))
        attrList.add(ModelAttr("classicstriped", "классический полосатый"))
        attrList.add(ModelAttr("classicv-neck", "классический вверх"))
        attrList.add(ModelAttr("classicwoven", "классический"))
        attrList.add(ModelAttr("clean", "без смысла"))
        attrList.add(ModelAttr("cleanwash", "без смысла"))
        attrList.add(ModelAttr("cloud", "облако"))
        attrList.add(ModelAttr("cloudwash", "легкая стирка"))
        attrList.add(ModelAttr("coast", "пляжная одежда"))
        attrList.add(ModelAttr("coated", "накидка"))
        attrList.add(ModelAttr("coffee", "кофе"))
        attrList.add(ModelAttr("collar", "воротник"))
        attrList.add(ModelAttr("collarlace", "воротник"))
        attrList.add(ModelAttr("collared", "воротник"))
        attrList.add(ModelAttr("collarless", "без воротника"))
        attrList.add(ModelAttr("collarlessfaux", "ошейники"))
        attrList.add(ModelAttr("colorblock", "трехцветный"))
        attrList.add(ModelAttr("colorblockpocket", "цвет блока карман"))
        attrList.add(ModelAttr("colorblocked", "цветные блоки"))
        attrList.add(ModelAttr("combo", "комбо"))
        attrList.add(ModelAttr("combomaxi", "комбинированный макси"))
        attrList.add(ModelAttr("contrast", "контрастная отделка"))
        attrList.add(ModelAttr("contrasttrim", "Антрим"))
        attrList.add(ModelAttr("contrast-trimmed", "контрастная отделка"))
        attrList.add(ModelAttr("convertible", "хамелеон"))
        attrList.add(ModelAttr("corduroy", "бархат"))
        attrList.add(ModelAttr("cotton", "хлопок"))
        attrList.add(ModelAttr("cottondrawstring", "хлопок"))
        attrList.add(ModelAttr("cottonknit", "вязаный"))
        attrList.add(ModelAttr("cotton-blend", "хлопковая смесь"))
        attrList.add(ModelAttr("cover-up", "скрытый карман"))
        attrList.add(ModelAttr("cowl", "капюшон"))
        attrList.add(ModelAttr("cowlneck", "воротник"))
        attrList.add(ModelAttr("cozy", "уютный"))
        attrList.add(ModelAttr("crepe", "креп"))
        attrList.add(ModelAttr("crepeshift", "креп"))
        attrList.add(ModelAttr("crepewoven", "крайован"))
        attrList.add(ModelAttr("crew", "без смысла"))
        attrList.add(ModelAttr("crewneck", "без смысла"))
        attrList.add(ModelAttr("crinkled", "мятый"))
        attrList.add(ModelAttr("crisscross", "пересекать"))
        attrList.add(ModelAttr("crisscross-back", "крест на спине"))
        attrList.add(ModelAttr("crochet", "вязаный крючком"))
        attrList.add(ModelAttr("crochetcrop", "вязаный крючком"))
        attrList.add(ModelAttr("crochetembroidered", "вязаный крючком"))
        attrList.add(ModelAttr("crochetfloral", "вязаный крючком"))
        attrList.add(ModelAttr("crochetfringe", "вязаный крючком"))
        attrList.add(ModelAttr("crochetknit", "вязаный крючком"))
        attrList.add(ModelAttr("crochetlace", "вязаный крючком"))
        attrList.add(ModelAttr("crochetmaxi", "вязаный крючком макси"))
        attrList.add(ModelAttr("crochetmesh", "вязаный крючком сетки"))
        attrList.add(ModelAttr("crochetoverlay", "вязаный крючком"))
        attrList.add(ModelAttr("crochet-paneled", "вязание крючком"))
        attrList.add(ModelAttr("crochet-trimmed", "элементы связанные крючком"))
        attrList.add(ModelAttr("crocheted", "вязанный"))
        attrList.add(ModelAttr("crochetedlace", "вязание крючком"))
        attrList.add(ModelAttr("crop", "урожай"))
        attrList.add(ModelAttr("cropped", "кадрированный"))
        attrList.add(ModelAttr("croppedknit", "укороченный трикотаж"))
        attrList.add(ModelAttr("cross-back", "крест на спине"))
        attrList.add(ModelAttr("crossback", "о крестоносцах"))
        attrList.add(ModelAttr("cuffed", "прикованный"))
        attrList.add(ModelAttr("cuffeddenim", "без смысла"))
        attrList.add(ModelAttr("cuffed-sleeve", "с манжетами"))
        attrList.add(ModelAttr("curved", "изогнутый"))
        attrList.add(ModelAttr("curvedhem", "асимметричныйворотник"))
        attrList.add(ModelAttr("cut", "вырез"))
        attrList.add(ModelAttr("cute", "милый"))
        attrList.add(ModelAttr("cutoff", "потертости"))
        attrList.add(ModelAttr("cutout", "вырез"))
        attrList.add(ModelAttr("cutoutlace", "вырез"))
        attrList.add(ModelAttr("cutoutmaxi", "вырез макси"))
        attrList.add(ModelAttr("cutoutsheath", "вырез оболочка"))
        attrList.add(ModelAttr("cutout-back", "сокращать"))
        attrList.add(ModelAttr("dainty", "дизайнерский"))
        attrList.add(ModelAttr("daisy", "цветочный принт"))
        attrList.add(ModelAttr("daisyprint", "цветочный принт"))
        attrList.add(ModelAttr("damask", "без смысла"))
        attrList.add(ModelAttr("daring", "мужской"))
        attrList.add(ModelAttr("dark", "темный"))
        attrList.add(ModelAttr("darling", "Дорогой"))
        attrList.add(ModelAttr("deepv-neck", "глубокий v-образный вырез"))
        attrList.add(ModelAttr("deep-v", "глубокий v-образный вырез"))
        attrList.add(ModelAttr("defyant", "без смысла"))
        attrList.add(ModelAttr("denim", "джинсовая ткань"))
        attrList.add(ModelAttr("denimdrawstring", "джинсовая ткань строка"))
        attrList.add(ModelAttr("denimpencil", "джинсовый с прямым кроем"))
        attrList.add(ModelAttr("denimshift", "деним"))
        attrList.add(ModelAttr("denimshirt", "джинсовая рубашка"))
        attrList.add(ModelAttr("denimskater", "Данис чер"))
        attrList.add(ModelAttr("denimutility", "джинсовая утилита"))
        attrList.add(ModelAttr("desert", "песочный цвет"))
        attrList.add(ModelAttr("destroyed", "без смысла"))
        attrList.add(ModelAttr("devil", "дьявол"))
        attrList.add(ModelAttr("diamond", "со стразами"))
        attrList.add(ModelAttr("diamondprint", "Алмазная печать"))
        attrList.add(ModelAttr("dip-dye", "принт"))
        attrList.add(ModelAttr("dip-dyed", "ухудшать"))
        attrList.add(ModelAttr("distressed", "без смысла"))
        attrList.add(ModelAttr("distressedlow-rise", "без смысла"))
        attrList.add(ModelAttr("distressedmid-rise", "высокий подъем"))
        attrList.add(ModelAttr("distressedskinny", "скинни"))
        attrList.add(ModelAttr("ditsy", "цветочный принт"))
        attrList.add(ModelAttr("ditsyfloral", "цветочный принт"))
        attrList.add(ModelAttr("ditsyfloralprint", "цветочный принт"))
        attrList.add(ModelAttr("doll", "кукла"))
        attrList.add(ModelAttr("dolman", "куртка со стоячим воротником"))
        attrList.add(ModelAttr("dolmansleeve", "куртка со стоячим воротником с потертостями"))
        attrList.add(ModelAttr("dolman-sleeve", "куртка со стоячим воротником и рукавами"))
        attrList.add(ModelAttr("dolphin", "дельфин"))
        attrList.add(ModelAttr("dolphinhem", "ариум Дельфин"))
        attrList.add(ModelAttr("doodle", "каракули"))
        attrList.add(ModelAttr("dot", "точки"))
        attrList.add(ModelAttr("dots", "точки"))
        attrList.add(ModelAttr("dotted", "тире"))
        attrList.add(ModelAttr("double-breasted", "двубортный"))
        attrList.add(ModelAttr("drape-front", "спереди драпировка"))
        attrList.add(ModelAttr("draped", "задрапированный"))
        attrList.add(ModelAttr("drapedopen-front", "спереди драпировка"))
        attrList.add(ModelAttr("drapedshawl", "картечь"))
        attrList.add(ModelAttr("drapedsurplice", "драпированные"))
        attrList.add(ModelAttr("drapey", "струящаяся ткань"))
        attrList.add(ModelAttr("drawstring", "кружево"))
        attrList.add(ModelAttr("dream", "домашняя одежда"))
        attrList.add(ModelAttr("dreamcatcher", "ловец снов"))
        attrList.add(ModelAttr("dreamer", "домашняя одежда"))
        attrList.add(ModelAttr("dropwaist", "низкая талия"))
        attrList.add(ModelAttr("drop-sleeve", "струящаяся ткань на руках"))
        attrList.add(ModelAttr("drop-waist", "низкая талия"))
        attrList.add(ModelAttr("dropped", "струящаяся ткань"))
        attrList.add(ModelAttr("dye", "цветное"))
        attrList.add(ModelAttr("dynamite", "динамит"))
        attrList.add(ModelAttr("eagle", "орёл"))
        attrList.add(ModelAttr("edge", "край"))
        attrList.add(ModelAttr("eiffel", "без смысла"))
        attrList.add(ModelAttr("elasticized", "облигающий"))
        attrList.add(ModelAttr("elegant", "элегантный"))
        attrList.add(ModelAttr("elephant", "принт слон"))
        attrList.add(ModelAttr("elephantprint", "принт слон"))
        attrList.add(ModelAttr("embellished", "украшенный"))
        attrList.add(ModelAttr("embroidered", "вышивка"))
        attrList.add(ModelAttr("embroideredfit", "вышивка"))
        attrList.add(ModelAttr("embroideredfloral", "цветочная вышивка"))
        attrList.add(ModelAttr("embroideredgauze", "вышитая марля"))
        attrList.add(ModelAttr("embroideredgauzepeasant", "вышитые марлевые крестьянина"))
        attrList.add(ModelAttr("embroideredlace", "кружева"))
        attrList.add(ModelAttr("embroideredmaxi", "макси с вышивкой"))
        attrList.add(ModelAttr("embroideredmesh", "сетка"))
        attrList.add(ModelAttr("embroideredpeasant", "крестьянкий стиль с вышивкой"))
        attrList.add(ModelAttr("embroideredshift", "вышивка"))
        attrList.add(ModelAttr("embroideredwoven", "вышивка"))
        attrList.add(ModelAttr("embroidery", "вышивка"))
        attrList.add(ModelAttr("enchanted", "контрастный"))
        attrList.add(ModelAttr("ethereal", "базовый"))
        attrList.add(ModelAttr("everyday", "повседневный"))
        attrList.add(ModelAttr("eyelash", "ресницы"))
        attrList.add(ModelAttr("eyelashknit", "ресницы"))
        attrList.add(ModelAttr("eyelashlace", "ресницы"))
        attrList.add(ModelAttr("eyelet", "с дырками"))
        attrList.add(ModelAttr("eyeletfit", "ресницы"))
        attrList.add(ModelAttr("faded", "нейтрального цвета"))
        attrList.add(ModelAttr("fair", "без смысла"))
        attrList.add(ModelAttr("fairisle", "шерсть"))
        attrList.add(ModelAttr("fan", "с дырками"))
        attrList.add(ModelAttr("fancy", "маскарад"))
        attrList.add(ModelAttr("faux", "искусственный"))
        attrList.add(ModelAttr("fauxfur", "искусственный мех"))
        attrList.add(ModelAttr("fauxleather", "искусственная кожа"))
        attrList.add(ModelAttr("fauxleathermini", "искусственная кожа мини"))
        attrList.add(ModelAttr("fauxleathermoto", "мото из искусственной кожи"))
        attrList.add(ModelAttr("fauxleatherpaneled", "искусственная кожа с защитой"))
        attrList.add(ModelAttr("fauxleatherpencil", "искусственная кожа прямой крой"))
        attrList.add(ModelAttr("fauxleatherskater", "спортивный из искусственной кожи"))
        attrList.add(ModelAttr("fauxleathervarsity", "искусственная кожа школьники"))
        attrList.add(ModelAttr("fauxleather-paneled", "защита из искусственной кожи"))
        attrList.add(ModelAttr("fauxleather-trimmed", "искусственная кожа"))
        attrList.add(ModelAttr("fauxshearling", "искусственная бахрома"))
        attrList.add(ModelAttr("fauxsuede", "искусственная замша"))
        attrList.add(ModelAttr("faux-wrap", "искусственный"))
        attrList.add(ModelAttr("feather", "рукав"))
        attrList.add(ModelAttr("festive", "маскарад"))
        attrList.add(ModelAttr("field", "одуванчик принт"))
        attrList.add(ModelAttr("fisherman", "спец одежда"))
        attrList.add(ModelAttr("fit", "аппликация"))
        attrList.add(ModelAttr("fitflare", "клеш"))
        attrList.add(ModelAttr("fitskinny", "Пиччини"))
        attrList.add(ModelAttr("fitted", "укороченный"))
        attrList.add(ModelAttr("fittedv-neck", "приталенный с v-образным вырезом"))
        attrList.add(ModelAttr("flare", "расклешенные"))
        attrList.add(ModelAttr("flared", "расклешенные"))
        attrList.add(ModelAttr("flat", "без смысла"))
        attrList.add(ModelAttr("flatfront", "без смысла"))
        attrList.add(ModelAttr("flat-front", "без смысла"))
        attrList.add(ModelAttr("flawless", "без смысла"))
        attrList.add(ModelAttr("flirty", "коктельный"))
        attrList.add(ModelAttr("floral", "цветочный принт"))
        attrList.add(ModelAttr("floralflutter", "летучая мышь"))
        attrList.add(ModelAttr("floralknit", "цветочный принт"))
        attrList.add(ModelAttr("florallace", "цветочные кружева"))
        attrList.add(ModelAttr("florallacemini", "цветочные кружева мини"))
        attrList.add(ModelAttr("florallacesheath", "цветочные кружева"))
        attrList.add(ModelAttr("florallaceskater", "кружева с вышивкой"))
        attrList.add(ModelAttr("floralmaxi", "цветочный принт макси"))
        attrList.add(ModelAttr("floralmesh", "цветочный принт"))
        attrList.add(ModelAttr("floralmidi", "цветочный принт"))
        attrList.add(ModelAttr("floralmini", "цветочный принт мини"))
        attrList.add(ModelAttr("floralpaisley", "цветочный принт"))
        attrList.add(ModelAttr("floralpattern", "цветочный принт"))
        attrList.add(ModelAttr("floralpeasant", "цветочный крестьянин"))
        attrList.add(ModelAttr("floralpleated", "цветочные плиссированные"))
        attrList.add(ModelAttr("floralprint", "цветочный принт"))
        attrList.add(ModelAttr("floralprintskater", "цветочный принт"))
        attrList.add(ModelAttr("floralprintstrapless", "цветочный принт без бретелек"))
        attrList.add(ModelAttr("floralprintsurplice", "цветочный принт"))
        attrList.add(ModelAttr("floralshift", "цветочный принт"))
        attrList.add(ModelAttr("floralskater", "цветочный принт"))
        attrList.add(ModelAttr("floralsurplice", "цветочным принт"))
        attrList.add(ModelAttr("floraltextured", "цветочный принт"))
        attrList.add(ModelAttr("floral-embroidered", "вышивка цветы"))
        attrList.add(ModelAttr("flounce", "оборка"))
        attrList.add(ModelAttr("flouncemaxi", "воланы макси"))
        attrList.add(ModelAttr("flounced", "струящаяся ткань"))
        attrList.add(ModelAttr("flower", "цветочный принт"))
        attrList.add(ModelAttr("flowy", "легкая струящаяся ткань"))
        attrList.add(ModelAttr("floyd", "Флойд"))
        attrList.add(ModelAttr("fluted", "гофрированный"))
        attrList.add(ModelAttr("flutter", "дрожать"))
        attrList.add(ModelAttr("fluttersleeve", "расклешенный рукав"))
        attrList.add(ModelAttr("flutter-sleeve", "расклешенный рукав"))
        attrList.add(ModelAttr("foil", "с металлической нитью"))
        attrList.add(ModelAttr("fold-over", "отложной"))
        attrList.add(ModelAttr("foldover", "вототник стойка"))
        attrList.add(ModelAttr("folk", "без смысла"))
        attrList.add(ModelAttr("folkprint", "поле принт"))
        attrList.add(ModelAttr("foulard", "баф"))
        attrList.add(ModelAttr("fox", "лисий мех"))
        attrList.add(ModelAttr("france", "французский стиль"))
        attrList.add(ModelAttr("frayed", "искусственно состаренный"))
        attrList.add(ModelAttr("freespirit", "свободный крой"))
        attrList.add(ModelAttr("french", "Французский стиль"))
        attrList.add(ModelAttr("frenchterry", "махровый халат"))
        attrList.add(ModelAttr("fresh", "без смысла"))
        attrList.add(ModelAttr("frida", "Фрида"))
        attrList.add(ModelAttr("fringe", "бахрома"))
        attrList.add(ModelAttr("fringed", "контрастный"))
        attrList.add(ModelAttr("fur", "мех"))
        attrList.add(ModelAttr("fuzzy", "размытый"))
        attrList.add(ModelAttr("fuzzyknit", "мягкий трикотаж"))
        attrList.add(ModelAttr("galaxy", "космос принт"))
        attrList.add(ModelAttr("garden", "цветочный принт"))
        attrList.add(ModelAttr("gardenparty", "вечерний с цветами"))
        attrList.add(ModelAttr("gatheredwaistline", "присборенная линия талии"))
        attrList.add(ModelAttr("gaucho", "гаучо"))
        attrList.add(ModelAttr("gauze", "ситец"))
        attrList.add(ModelAttr("gauzemaxi", "домашняя одежда"))
        attrList.add(ModelAttr("gauzepeasant", "домашняя одежда цветная"))
        attrList.add(ModelAttr("gauzy", "прозрачный"))
        attrList.add(ModelAttr("gem", "со стразами"))
        attrList.add(ModelAttr("genuine", "с драгоценными камнями"))
        attrList.add(ModelAttr("geo", "без смысла"))
        attrList.add(ModelAttr("geopattern", "без смысла"))
        attrList.add(ModelAttr("geoprint", "без смысла"))
        attrList.add(ModelAttr("geostripe", "полосы"))
        attrList.add(ModelAttr("georgette", "зонтик"))
        attrList.add(ModelAttr("gingham", "зонтик"))
        attrList.add(ModelAttr("giraffe", "жираф принт"))
        attrList.add(ModelAttr("giraffeprint", "жираф принт"))
        attrList.add(ModelAttr("girl", "девочка"))
        attrList.add(ModelAttr("girls", "девочка"))
        attrList.add(ModelAttr("glass", "очки"))
        attrList.add(ModelAttr("glitter", "с паетками"))
        attrList.add(ModelAttr("graphic", "графический"))
        attrList.add(ModelAttr("graphicmuscle", "мышцы принт"))
        attrList.add(ModelAttr("graphicracerback", "принт гонщик на спине"))
        attrList.add(ModelAttr("grid", "сетка"))
        attrList.add(ModelAttr("gridprint", "сетка"))
        attrList.add(ModelAttr("grunge", "вельвет"))
        attrList.add(ModelAttr("guns", "пилотка"))
        attrList.add(ModelAttr("halen", "без смысла"))
        attrList.add(ModelAttr("harem", "без смысла"))
        attrList.add(ModelAttr("heart", "сердце принт"))
        attrList.add(ModelAttr("heartprint", "сердце принт"))
        attrList.add(ModelAttr("heat", "зимний, демисезонный"))
        attrList.add(ModelAttr("heathered", "меланж"))
        attrList.add(ModelAttr("heatheredknit", "меланж"))
        attrList.add(ModelAttr("heatheredstripe", "лампасы"))
        attrList.add(ModelAttr("heatheredv-neck", "v-образный вырез"))
        attrList.add(ModelAttr("hem", "кант"))
        attrList.add(ModelAttr("hepburn", "Хепберн"))
        attrList.add(ModelAttr("heroes", "костюмы героев"))
        attrList.add(ModelAttr("herringbone", "рождество"))
        attrList.add(ModelAttr("high-low", "длина 3/4"))
        attrList.add(ModelAttr("high-neck", "высокий воротник"))
        attrList.add(ModelAttr("high-rise", "высокий"))
        attrList.add(ModelAttr("high-riseskinny", "высокий"))
        attrList.add(ModelAttr("high-slit", "глубокий вырез"))
        attrList.add(ModelAttr("high-slitmaxi", "экстремальные условия"))
        attrList.add(ModelAttr("high-waist", "высокая талия"))
        attrList.add(ModelAttr("high-waisted", "высокая талия"))
        attrList.add(ModelAttr("hood", "капюшон"))
        attrList.add(ModelAttr("hooded", "худи"))
        attrList.add(ModelAttr("hoodedmaxi", "худи с капюшоном"))
        attrList.add(ModelAttr("hoodedutility", "худи с капюшоном"))
        attrList.add(ModelAttr("houndstooth", "гусиные лапки (орнамент)"))
        attrList.add(ModelAttr("ikat", "икат"))
        attrList.add(ModelAttr("ikatprint", "икат принт"))
        attrList.add(ModelAttr("illusion", "иллюзия"))
        attrList.add(ModelAttr("illusionneckline", "иллюзия линии шеи"))
        attrList.add(ModelAttr("inset", "без смысла"))
        attrList.add(ModelAttr("internet", "без смысла"))
        attrList.add(ModelAttr("island", "из ласкутов"))
        attrList.add(ModelAttr("isle", "из ласкутов"))
        attrList.add(ModelAttr("jacquard", "жаккард"))
        attrList.add(ModelAttr("joie", "маскарад"))
        attrList.add(ModelAttr("kahlo", "Кало"))
        attrList.add(ModelAttr("kaleidoscope", "калейдоскоп"))
        attrList.add(ModelAttr("kaleidoscopeprint", "калейдоскоп принт"))
        attrList.add(ModelAttr("kangaroo", "кенгуру карман"))
        attrList.add(ModelAttr("kangaroopocket", "кенгуру карман"))
        attrList.add(ModelAttr("keyhole", "плотный материал"))
        attrList.add(ModelAttr("kid", "детский"))
        attrList.add(ModelAttr("killin", "Киллин"))
        attrList.add(ModelAttr("kiss", "поцелуи принт"))
        attrList.add(ModelAttr("kitty", "котёнок"))
        attrList.add(ModelAttr("knee-length", "длина до колен"))
        attrList.add(ModelAttr("knit", "вязать"))
        attrList.add(ModelAttr("knitlace", "трикотаж"))
        attrList.add(ModelAttr("knitlongline", "вязаный макси"))
        attrList.add(ModelAttr("knitmaxi", "вязаный макси"))
        attrList.add(ModelAttr("knitmini", "вязаный мини"))
        attrList.add(ModelAttr("knitopen", "вязаный открыть"))
        attrList.add(ModelAttr("knitpencil", "капенсис"))
        attrList.add(ModelAttr("knitpocket", "вязаный карман"))
        attrList.add(ModelAttr("knitraglan", "без смысла"))
        attrList.add(ModelAttr("knitshawl", "вязаная шаль"))
        attrList.add(ModelAttr("knitskater", "вязаная стер"))
        attrList.add(ModelAttr("knitstripe", "трикотаж в полоску"))
        attrList.add(ModelAttr("knitstriped", "вязаный в полоску"))
        attrList.add(ModelAttr("knittrapeze", "вязаная трапеция"))
        attrList.add(ModelAttr("knitv-neck", "вязанный с v-образным вырезом"))
        attrList.add(ModelAttr("knotted", "вязанный"))
        attrList.add(ModelAttr("kurt", "Курт"))
        attrList.add(ModelAttr("la", "французский стиль"))
        attrList.add(ModelAttr("lace", "кружево"))
        attrList.add(ModelAttr("lacelayered", "кружево слоями"))
        attrList.add(ModelAttr("lacemaxi", "кружево макси"))
        attrList.add(ModelAttr("lacemesh", "кружевная сетка"))
        attrList.add(ModelAttr("lacemidi", "кружева миди"))
        attrList.add(ModelAttr("lacemini", "вставки мини"))
        attrList.add(ModelAttr("laceoverlay", "кружевные вставки"))
        attrList.add(ModelAttr("lacepanel", "кружево"))
        attrList.add(ModelAttr("lacepaneled", "кружево"))
        attrList.add(ModelAttr("lacepencil", "кружево"))
        attrList.add(ModelAttr("lacepeplum", "кружевная баска"))
        attrList.add(ModelAttr("lacepleated", "ажурный"))
        attrList.add(ModelAttr("laceprint", "кружевной принт"))
        attrList.add(ModelAttr("lacesheath", "кружевной"))
        attrList.add(ModelAttr("lacesheer", "кружевной прозрачные"))
        attrList.add(ModelAttr("laceshift", "кружево"))
        attrList.add(ModelAttr("laceskater", "кружево"))
        attrList.add(ModelAttr("lacesleeve", "кружевной рукав"))
        attrList.add(ModelAttr("lacetrim", "кружевная вставка"))
        attrList.add(ModelAttr("lace-paneled", "кружевная вставка"))
        attrList.add(ModelAttr("lace-trim", "кружевная вставка"))
        attrList.add(ModelAttr("lace-trimmed", "кружевная вставка"))
        attrList.add(ModelAttr("lace-up", "шнуровка"))
        attrList.add(ModelAttr("lacy", "кружево"))
        attrList.add(ModelAttr("ladder-back", "кружево на спине"))
        attrList.add(ModelAttr("lady", "женский"))
        attrList.add(ModelAttr("lakers", "Лейкеры"))
        attrList.add(ModelAttr("lapel", "лацкан"))
        attrList.add(ModelAttr("laser", "лазер"))
        attrList.add(ModelAttr("lattice", "решетка"))
        attrList.add(ModelAttr("layered", "пышный"))
        attrList.add(ModelAttr("leaf", "лист"))
        attrList.add(ModelAttr("leafprint", "лист принт"))
        attrList.add(ModelAttr("leather", "кожа"))
        attrList.add(ModelAttr("leathermini", "кожаный мини"))
        attrList.add(ModelAttr("leathermoto", "кожаная байкерская"))
        attrList.add(ModelAttr("leatherpaneled", "искусственная кожа"))
        attrList.add(ModelAttr("leatherpencil", "Кожевник"))
        attrList.add(ModelAttr("leatherpeplum", "искусственная кожа"))
        attrList.add(ModelAttr("leatherquilted", "кожаные стеганые"))
        attrList.add(ModelAttr("leatherskater", "кожаный"))
        attrList.add(ModelAttr("leathertrimmed", "искусственная кожа"))
        attrList.add(ModelAttr("leathervarsity", "кожаный"))
        attrList.add(ModelAttr("leather-paneled", "кожа-филенчатые"))
        attrList.add(ModelAttr("leather-trimmed", "кожаная отделка"))
        attrList.add(ModelAttr("leave", "струящаяся ткань"))
        attrList.add(ModelAttr("led", "светлый"))
        attrList.add(ModelAttr("leopard", "леопардовый"))
        attrList.add(ModelAttr("leopardprint", "леопардовый"))
        attrList.add(ModelAttr("life", "повседневный"))
        attrList.add(ModelAttr("light", "светлый"))
        attrList.add(ModelAttr("lightning", "молния"))
        attrList.add(ModelAttr("linen", "белье"))
        attrList.add(ModelAttr("linen-blend", "льняная смесь"))
        attrList.add(ModelAttr("logo", "логотип"))
        attrList.add(ModelAttr("longsleeve", "футболка с длинным рукавом"))
        attrList.add(ModelAttr("long-sleeve", "длинный рукав"))
        attrList.add(ModelAttr("long-sleeved", "длинный рукав"))
        attrList.add(ModelAttr("longline", "пышный"))
        attrList.add(ModelAttr("longlineshirt", "длинная рубашка"))
        attrList.add(ModelAttr("loop", "шлейф"))
        attrList.add(ModelAttr("loose", "свободный крой"))
        attrList.add(ModelAttr("loose-knit", "свободный крой трикотаж"))
        attrList.add(ModelAttr("lounge", "гостинная"))
        attrList.add(ModelAttr("love", "любовь"))
        attrList.add(ModelAttr("lover", "любовник"))
        attrList.add(ModelAttr("low-rise", "низкая посадка"))
        attrList.add(ModelAttr("low-riseskinny", "облегающий с низкой посадкой"))
        attrList.add(ModelAttr("loyal", "лояльный"))
        attrList.add(ModelAttr("luxe", "люкс"))
        attrList.add(ModelAttr("m-slit", "м-слот"))
        attrList.add(ModelAttr("m-slitmaxi", "м-макси"))
        attrList.add(ModelAttr("mandala", "мандалы"))
        attrList.add(ModelAttr("mandalaprint", "модель печати"))
        attrList.add(ModelAttr("mandarin", "мандарин"))
        attrList.add(ModelAttr("map", "карта"))
        attrList.add(ModelAttr("marble", "мрамор"))
        attrList.add(ModelAttr("marbleprint", "мраморная печать"))
        attrList.add(ModelAttr("marilyn", "Мэрилин"))
        attrList.add(ModelAttr("marilynmonroe", "Мэрилин Монро"))
        attrList.add(ModelAttr("marled", "постоплатной"))
        attrList.add(ModelAttr("marledstripe", "ситец"))
        attrList.add(ModelAttr("matelot", "Мателот"))
        attrList.add(ModelAttr("maxi", "макси"))
        attrList.add(ModelAttr("medallion", "медальон"))
        attrList.add(ModelAttr("medallionprint", "андийская мидл"))
        attrList.add(ModelAttr("medium", "средний"))
        attrList.add(ModelAttr("meow", "мяу"))
        attrList.add(ModelAttr("mesh", "шлейф"))
        attrList.add(ModelAttr("meshoverlay", "масурли"))
        attrList.add(ModelAttr("meshpanel", "ситец"))
        attrList.add(ModelAttr("meshpaneled", "ситец"))
        attrList.add(ModelAttr("meshracerback", "ситец гонки"))
        attrList.add(ModelAttr("mesh-paneled", "сетка"))
        attrList.add(ModelAttr("mesh-trimmed", "сетка"))
        attrList.add(ModelAttr("metallic", "металл"))
        attrList.add(ModelAttr("miami", "Майами"))
        attrList.add(ModelAttr("mickey", "Микки"))
        attrList.add(ModelAttr("mickeymouse", "Микки Маус"))
        attrList.add(ModelAttr("midrise", "проект"))
        attrList.add(ModelAttr("midriseskinny", "низкая посадка облегающий"))
        attrList.add(ModelAttr("mid-rise", "средний рост"))
        attrList.add(ModelAttr("mid-riseskinny", "средний рост"))
        attrList.add(ModelAttr("midi", "миди"))
        attrList.add(ModelAttr("mina", "мой"))
        attrList.add(ModelAttr("mineral", "минеральный"))
        attrList.add(ModelAttr("mineralwash", "минеральная промывка"))
        attrList.add(ModelAttr("mini", "мини"))
        attrList.add(ModelAttr("minnie", "Минни"))
        attrList.add(ModelAttr("minniemouse", "Минни Маус"))
        attrList.add(ModelAttr("mirrored", "отражающий"))
        attrList.add(ModelAttr("mixed", "смешанный"))
        attrList.add(ModelAttr("mixedprint", "смешанная печать"))
        attrList.add(ModelAttr("mixedstripe", "смешанная полоса"))
        attrList.add(ModelAttr("mob", "толпа"))
        attrList.add(ModelAttr("mock", "ассиметричный"))
        attrList.add(ModelAttr("mockneck", "асимметричный вырез"))
        attrList.add(ModelAttr("mock-neck", "воротник-стойка"))
        attrList.add(ModelAttr("mod", "ультрасовременный"))
        attrList.add(ModelAttr("modernist", "модернист"))
        attrList.add(ModelAttr("monroe", "Монро"))
        attrList.add(ModelAttr("moon", "луна"))
        attrList.add(ModelAttr("morning", "утро"))
        attrList.add(ModelAttr("mosaic", "мозаичный"))
        attrList.add(ModelAttr("mosaicprint", "мозаичным принтом"))
        attrList.add(ModelAttr("moto", "мото"))
        attrList.add(ModelAttr("multi-stripe", "многодиапазонный"))
        attrList.add(ModelAttr("muscle", "мускул"))
        attrList.add(ModelAttr("muse", "муза"))
        attrList.add(ModelAttr("nautical", "навигационный"))
        attrList.add(ModelAttr("nauticalstripe", "морская полоса"))
        attrList.add(ModelAttr("nauticalstriped", "морской полосатый"))
        attrList.add(ModelAttr("neckribbed", "воротник с паетками"))
        attrList.add(ModelAttr("neckskater", "шейный конькобежец"))
        attrList.add(ModelAttr("neckstriped", "воротник полосатый"))
        attrList.add(ModelAttr("neckline", "с воротником"))
        attrList.add(ModelAttr("neon", "неоновый"))
        attrList.add(ModelAttr("neoprene", "неопрен"))
        attrList.add(ModelAttr("nets", "сетка"))
        attrList.add(ModelAttr("netted", "сетка"))
        attrList.add(ModelAttr("newyork", "Нью-Йорк"))
        attrList.add(ModelAttr("night", "ночь"))
        attrList.add(ModelAttr("notchedcollar", "воротник с шипами"))
        attrList.add(ModelAttr("notorious", "пресловутый"))
        attrList.add(ModelAttr("ny", "Нью-Йорк"))
        attrList.add(ModelAttr("nyc", "Нью-Йорк"))
        attrList.add(ModelAttr("nylon", "нейлон"))
        attrList.add(ModelAttr("off-the-shoulder", "с открытым плечом"))
        attrList.add(ModelAttr("oil", "масло"))
        attrList.add(ModelAttr("ombre", "Омбре"))
        attrList.add(ModelAttr("one-button", "одна кнопка"))
        attrList.add(ModelAttr("one-shoulder", "с открытым плечом"))
        attrList.add(ModelAttr("open-back", "открытая спина"))
        attrList.add(ModelAttr("open-front", "открытый перед"))
        attrList.add(ModelAttr("open-knit", "ажурный трикотаж"))
        attrList.add(ModelAttr("open-shoulder", "с открытыми плечами"))
        attrList.add(ModelAttr("organza", "Органза"))
        attrList.add(ModelAttr("origami", "оригами"))
        attrList.add(ModelAttr("ornate", "витиеватый"))
        attrList.add(ModelAttr("ornatepaisley", "витиеватый"))
        attrList.add(ModelAttr("ornateprint", "принт"))
        attrList.add(ModelAttr("overlay", "над кругом"))
        attrList.add(ModelAttr("overlaysheath", "с подкладкой"))
        attrList.add(ModelAttr("oversized", "по размеру"))
        attrList.add(ModelAttr("oxford", "Оксфорд"))
        attrList.add(ModelAttr("paint", "красить"))
        attrList.add(ModelAttr("paintsplatter", "брызги краски"))
        attrList.add(ModelAttr("painted", "окрашенный"))
        attrList.add(ModelAttr("paisley", "Пейсли"))
        attrList.add(ModelAttr("paisleyprint", "Пейсли"))
        attrList.add(ModelAttr("palm", "ладонь"))
        attrList.add(ModelAttr("palmprint", "отпечаток ладони"))
        attrList.add(ModelAttr("palmsprings", "вы можете оставить"))
        attrList.add(ModelAttr("palmtree", "ладонь"))
        attrList.add(ModelAttr("pan", "кастрюля"))
        attrList.add(ModelAttr("panel", "панель"))
        attrList.add(ModelAttr("paneled", "со строчкой"))
        attrList.add(ModelAttr("paradise", "парадайс"))
        attrList.add(ModelAttr("paris", "Париж"))
        attrList.add(ModelAttr("party", "сторона"))
        attrList.add(ModelAttr("patched", "исправленный"))
        attrList.add(ModelAttr("patchwork", "работа патч"))
        attrList.add(ModelAttr("pattern", "шаблон"))
        attrList.add(ModelAttr("patterned", "фигурный"))
        attrList.add(ModelAttr("peasant", "крестьянин"))
        attrList.add(ModelAttr("pencil", "карандаш"))
        attrList.add(ModelAttr("peplum", "Баск"))
        attrList.add(ModelAttr("perforated", "перфорированный"))
        attrList.add(ModelAttr("performance", "спектакль"))
        attrList.add(ModelAttr("pima", "индейцы"))
        attrList.add(ModelAttr("pin", "пин"))
        attrList.add(ModelAttr("pineapple", "ананас"))
        attrList.add(ModelAttr("pink", "розовый"))
        attrList.add(ModelAttr("pinstripe", "полосатый"))
        attrList.add(ModelAttr("pinstriped", "в тонкую полоску"))
        attrList.add(ModelAttr("pintuck", "с зажимами"))
        attrList.add(ModelAttr("pintuckpleated", "плиссированный"))
        attrList.add(ModelAttr("pintucked", "с щипками"))
        attrList.add(ModelAttr("pizza", "пицца"))
        attrList.add(ModelAttr("pj", "PJ"))
        attrList.add(ModelAttr("plaid", "плед"))
        attrList.add(ModelAttr("plaidshirt", "клетчатая рубашка"))
        attrList.add(ModelAttr("please", "пожалуйста"))
        attrList.add(ModelAttr("pleat", "сгибать"))
        attrList.add(ModelAttr("pleated", "плиссированный"))
        attrList.add(ModelAttr("pleatedskater", "плиссированные фигурист"))
        attrList.add(ModelAttr("pleatedwoven", "плиссированный"))
        attrList.add(ModelAttr("pocket", "карман"))
        attrList.add(ModelAttr("pointelle", "ажур"))
        attrList.add(ModelAttr("polkadot", "улица"))
        attrList.add(ModelAttr("polo", "поло"))
        attrList.add(ModelAttr("pom-pom", "помпон"))
        attrList.add(ModelAttr("ponte", "Понт"))
        attrList.add(ModelAttr("popcorn", "попкорн"))
        attrList.add(ModelAttr("popover", "рулон"))
        attrList.add(ModelAttr("posh", "шикарный"))
        attrList.add(ModelAttr("power", "сила"))
        attrList.add(ModelAttr("print", "принт"))
        attrList.add(ModelAttr("printracerback", "принт гонщик на спине"))
        attrList.add(ModelAttr("printsatin", "Принстон"))
        attrList.add(ModelAttr("printscuba", "принт акваланга"))
        attrList.add(ModelAttr("printshift", "принт"))
        attrList.add(ModelAttr("printshirt", "рубашка с принтом"))
        attrList.add(ModelAttr("printskater", "принт конькобежец"))
        attrList.add(ModelAttr("printsmock", "принт врежь"))
        attrList.add(ModelAttr("printsmocked", "присборенная"))
        attrList.add(ModelAttr("printstrapless", "принт без бретелек"))
        attrList.add(ModelAttr("printstrappy", "принт ремешками"))
        attrList.add(ModelAttr("printsurplice", "принт"))
        attrList.add(ModelAttr("printtulip", "принт тюльпан"))
        attrList.add(ModelAttr("printv-neck", "принт v-образным вырезом"))
        attrList.add(ModelAttr("printwoven", "принт тканые"))
        attrList.add(ModelAttr("printed", "принт"))
        attrList.add(ModelAttr("puffer", "Иглобрюх"))
        attrList.add(ModelAttr("pullover", "пуловер"))
        attrList.add(ModelAttr("purl", "ропот"))
        attrList.add(ModelAttr("quilted", "стеганый"))
        attrList.add(ModelAttr("quirky", "оригинальный"))
        attrList.add(ModelAttr("racerback", "единоборство"))
        attrList.add(ModelAttr("rad", "радостный"))
        attrList.add(ModelAttr("raga", "рага"))
        attrList.add(ModelAttr("raglan", "реглан"))
        attrList.add(ModelAttr("raglansleeve", "рукав реглан"))
        attrList.add(ModelAttr("rainbow", "радуга"))
        attrList.add(ModelAttr("raw", "сырой"))
        attrList.add(ModelAttr("raw-cut", "сырой"))
        attrList.add(ModelAttr("rebel", "бунт"))
        attrList.add(ModelAttr("red", "красный"))
        attrList.add(ModelAttr("refined", "утонченный"))
        attrList.add(ModelAttr("regime", "форма"))
        attrList.add(ModelAttr("relaxed", "свободный крой"))
        attrList.add(ModelAttr("retro", "ретро"))
        attrList.add(ModelAttr("reverse", "обратный"))
        attrList.add(ModelAttr("reversible", "обратимый"))
        attrList.add(ModelAttr("rhinestone", "горный хрусталь"))
        attrList.add(ModelAttr("rib", "ребристый"))
        attrList.add(ModelAttr("rib-knit", "ребристая вязка"))
        attrList.add(ModelAttr("ribbed", "ребристый"))
        attrList.add(ModelAttr("ribbedstripe", "ребристая полоса"))
        attrList.add(ModelAttr("ribbed-knit", "ребристый трикотаж"))
        attrList.add(ModelAttr("ringer", "звонарь"))
        attrList.add(ModelAttr("ripped", "порванный"))
        attrList.add(ModelAttr("rise", "высокая талия"))
        attrList.add(ModelAttr("riseskinny", "высокая талия облегающий"))
        attrList.add(ModelAttr("roll", "колесо"))
        attrList.add(ModelAttr("rolling", "катающийся"))
        attrList.add(ModelAttr("rollingstones", "роллингстоун"))
        attrList.add(ModelAttr("roman", "Римский"))
        attrList.add(ModelAttr("rose", "розы"))
        attrList.add(ModelAttr("roseskater", "россетер"))
        attrList.add(ModelAttr("roses", "розы"))
        attrList.add(ModelAttr("round", "круглый"))
        attrList.add(ModelAttr("ruched", "рюши"))
        attrList.add(ModelAttr("ruffle", "воланы"))
        attrList.add(ModelAttr("ruffletrim", "с отражателями"))
        attrList.add(ModelAttr("ruffled", "взъерошенный"))
        attrList.add(ModelAttr("rugby", "регби"))
        attrList.add(ModelAttr("rugbystripe", "полоса регби"))
        attrList.add(ModelAttr("rugbystriped", "регби полосатый"))
        attrList.add(ModelAttr("run", "для бега"))
        attrList.add(ModelAttr("running", "для бега"))
        attrList.add(ModelAttr("rustic", "деревня"))
        attrList.add(ModelAttr("safari", "сафари"))
        attrList.add(ModelAttr("sateen", "сатин"))
        attrList.add(ModelAttr("satin", "сатин"))
        attrList.add(ModelAttr("scallop", "гребешок"))
        attrList.add(ModelAttr("scalloped", "зуб"))
        attrList.add(ModelAttr("scoop", "совок"))
        attrList.add(ModelAttr("scoop-neck", "совок"))
        attrList.add(ModelAttr("scuba", "акваланг"))
        attrList.add(ModelAttr("scubaskater", "подшкалер"))
        attrList.add(ModelAttr("sea", "море"))
        attrList.add(ModelAttr("seam", "шов"))
        attrList.add(ModelAttr("seamless", "бесшовный"))
        attrList.add(ModelAttr("seaside", "побережье"))
        attrList.add(ModelAttr("seersucker", "полосатый"))
        attrList.add(ModelAttr("self-tie", "self-галстук"))
        attrList.add(ModelAttr("semi-sheer", "полупрозрачный"))
        attrList.add(ModelAttr("sequin", "с блестками"))
        attrList.add(ModelAttr("sequined", "с блестками"))
        attrList.add(ModelAttr("shaggy", "косматый"))
        attrList.add(ModelAttr("shark", "акула"))
        attrList.add(ModelAttr("shawl", "шаль"))
        attrList.add(ModelAttr("shearling", "ягненок"))
        attrList.add(ModelAttr("sheath", "ракушка"))
        attrList.add(ModelAttr("sheer", "свободного кроя"))
        attrList.add(ModelAttr("sheer-paneled", "прозрачный"))
        attrList.add(ModelAttr("shift", "ассиметричный"))
        attrList.add(ModelAttr("shirred", "гофрированный"))
        attrList.add(ModelAttr("shirt", "рубашка"))
        attrList.add(ModelAttr("shopping", "поход по магазинам"))
        attrList.add(ModelAttr("shore", "побережье"))
        attrList.add(ModelAttr("shoulder", "плечо"))
        attrList.add(ModelAttr("shredded", "с разрезами"))
        attrList.add(ModelAttr("sideslit", "боковой разрез"))
        attrList.add(ModelAttr("side-slit", "боковой разрез"))
        attrList.add(ModelAttr("single-button", "одно нажатие"))
        attrList.add(ModelAttr("skater", "конькобежец"))
        attrList.add(ModelAttr("skinny", "облигающий"))
        attrList.add(ModelAttr("skinnystretch", "облигающий стрейч"))
        attrList.add(ModelAttr("skort", "укороченный"))
        attrList.add(ModelAttr("sky", "небо"))
        attrList.add(ModelAttr("sleek", "гладкий"))
        attrList.add(ModelAttr("sleeve", "рукав"))
        attrList.add(ModelAttr("sleeveless", "без рукавов"))
        attrList.add(ModelAttr("slick", "скользкий"))
        attrList.add(ModelAttr("slim", "тонкий"))
        attrList.add(ModelAttr("slip", "горка"))
        attrList.add(ModelAttr("slit", "слот"))
        attrList.add(ModelAttr("slouchy", "громоздкий"))
        attrList.add(ModelAttr("slub", "Клуб"))
        attrList.add(ModelAttr("slub-knit", "Клубная вязка"))
        attrList.add(ModelAttr("smart", "умный"))
        attrList.add(ModelAttr("smile", "улыбка"))
        attrList.add(ModelAttr("smock", "рубашка"))
        attrList.add(ModelAttr("smocked", "смонтированный"))
        attrList.add(ModelAttr("snap", "щелчок"))
        attrList.add(ModelAttr("snoopy", "Выслеживающий"))
        attrList.add(ModelAttr("soft", "мягкий"))
        attrList.add(ModelAttr("solid", "твердый"))
        attrList.add(ModelAttr("sophisticated", "утонченный"))
        attrList.add(ModelAttr("southwestern", "юго-западный"))
        attrList.add(ModelAttr("southwestern-inspired", "пляжный вдохновленный"))
        attrList.add(ModelAttr("southwestern-patterned", "пляжный с узором"))
        attrList.add(ModelAttr("southwestern-print", "ковбой"))
        attrList.add(ModelAttr("sparkling", "сверкающий"))
        attrList.add(ModelAttr("speckled", "пестрый"))
        attrList.add(ModelAttr("spirit", "дух"))
        attrList.add(ModelAttr("splatter", "спрей"))
        attrList.add(ModelAttr("split", "разрез"))
        attrList.add(ModelAttr("split-back", "разрез на спине"))
        attrList.add(ModelAttr("split-neck", "разрез"))
        attrList.add(ModelAttr("spongebob", "Губка Боб"))
        attrList.add(ModelAttr("sporty", "спортивный"))
        attrList.add(ModelAttr("spotted", "пятнистый"))
        attrList.add(ModelAttr("springs", "пружины"))
        attrList.add(ModelAttr("square", "область"))
        attrList.add(ModelAttr("standout", "яркий"))
        attrList.add(ModelAttr("star", "звезды"))
        attrList.add(ModelAttr("stars", "звезды"))
        attrList.add(ModelAttr("stone", "камень"))
        attrList.add(ModelAttr("stonewashed", "побеленный"))
        attrList.add(ModelAttr("stones", "камни"))
        attrList.add(ModelAttr("straight-leg", "прямая нога"))
        attrList.add(ModelAttr("strap", "пояс"))
        attrList.add(ModelAttr("strapless", "без бретелек"))
        attrList.add(ModelAttr("straplesstribal", "с перфорацией"))
        attrList.add(ModelAttr("strappy", "ремни"))
        attrList.add(ModelAttr("stretch", "степень"))
        attrList.add(ModelAttr("stretch-knit", "эластичный трикотаж"))
        attrList.add(ModelAttr("stripe", "группа"))
        attrList.add(ModelAttr("striped", "полосатый"))
        attrList.add(ModelAttr("stripedtrapeze", "полосатый трапеция"))
        attrList.add(ModelAttr("stripedv-neck", "полосатый v-образный вырез"))
        attrList.add(ModelAttr("stripes", "подтеки"))
        attrList.add(ModelAttr("structured", "структурированный"))
        attrList.add(ModelAttr("studded", "обитый"))
        attrList.add(ModelAttr("studio", "ателье"))
        attrList.add(ModelAttr("suede", "замша"))
        attrList.add(ModelAttr("summer", "лето"))
        attrList.add(ModelAttr("sun", "солнце"))
        attrList.add(ModelAttr("sunburst", "солнце"))
        attrList.add(ModelAttr("sunflower", "подсолнечник"))
        attrList.add(ModelAttr("surfer", "серфер"))
        attrList.add(ModelAttr("surplice", "без смысла"))
        attrList.add(ModelAttr("suspender", "подвеска"))
        attrList.add(ModelAttr("sweet", "сладкий"))
        attrList.add(ModelAttr("sweetheart", "возлюбленная"))
        attrList.add(ModelAttr("swim", "плавать"))
        attrList.add(ModelAttr("swing", "трясти"))
        attrList.add(ModelAttr("swiss", "Швейцарский"))
        attrList.add(ModelAttr("t-back", "Т-образная спинка"))
        attrList.add(ModelAttr("taco", "тако"))
        attrList.add(ModelAttr("tapestry", "гобелен"))
        attrList.add(ModelAttr("tartan", "плед"))
        attrList.add(ModelAttr("tasmanian", "Тасмания"))
        attrList.add(ModelAttr("tassel", "щетка"))
        attrList.add(ModelAttr("tasseled", "щетка"))
        attrList.add(ModelAttr("terry", "двойной"))
        attrList.add(ModelAttr("texas", "Техас"))
        attrList.add(ModelAttr("textured", "текстурированный"))
        attrList.add(ModelAttr("texturedwoven", "текстурированный"))
        attrList.add(ModelAttr("thermal", "тепловой"))
        attrList.add(ModelAttr("tie-back", "галстук обратно"))
        attrList.add(ModelAttr("tie-dye", "галстук цветной"))
        attrList.add(ModelAttr("tie-front", "галстук"))
        attrList.add(ModelAttr("tie-neck", "галстук"))
        attrList.add(ModelAttr("tiered", "многоуровневый"))
        attrList.add(ModelAttr("tile", "плитка"))
        attrList.add(ModelAttr("toggle", "тумблер"))
        attrList.add(ModelAttr("tokyo", "Токио"))
        attrList.add(ModelAttr("tonal", "тональный"))
        attrList.add(ModelAttr("topstitched", "Настрочить"))
        attrList.add(ModelAttr("tower", "башня"))
        attrList.add(ModelAttr("track", "дорожка"))
        attrList.add(ModelAttr("training", "обучение"))
        attrList.add(ModelAttr("trapeze", "трапеция"))

    }

    fun getList() = attrList

    fun getRus(eng: String): String {
        attrList.forEach {
            if(it.eng.toUpperCase() == eng.toUpperCase()) return it.rus
        }
        return eng
    }

    fun isset(eng: String): Boolean {
        attrList.forEach {
            if(it.eng.toUpperCase() == eng.toUpperCase()) return true
        }
        return false
    }
}